import Foundation

/// What the app remembers about one message once it has read it.
///
/// Note what isn't here: the body. This file holds conclusions — a line
/// about what you might do, a sentence on what the message is about, and
/// when it's due — never the message. The body exists in memory for as long
/// as it takes the model to read it and nowhere else (see
/// `MailMessage.bodyExcerpt`), so the only full copy of your mail on this
/// Mac stays Mail's own.
///
/// `gist` is the closest this comes to the line: it is a paraphrase, a
/// sentence or two of what the message says, and it is written to disk.
/// That's a deliberate trade for the popover being useful the moment it
/// opens rather than after a second of the model thinking — but it is the
/// reason this file is worth being careful with, and why nothing longer
/// than a sentence or two ever goes in it.
///
/// Caching the body would make regeneration cheap, and that is exactly the
/// trade being refused: re-reading Mail costs seconds, and holding your
/// correspondence in a JSON file costs rather more than that.
struct MailSummary: Codable, Equatable {
    /// Mail's `message id` — stable across launches, which is the whole
    /// reason a cache is possible.
    let messageID: String
    /// One line, written to the reader: what *they* might do about this.
    /// Empty on a Mac with no on-device model, where the row falls back to
    /// the sender and subject it already has.
    var action: String
    /// What the message is about, in a sentence or two, for the popover —
    /// so you can decide what to do without opening Mail. Empty where
    /// there's no model, or where what came back didn't survive checking.
    var gist: String
    var dueDate: Date?
    var needsReply: Bool
    var savedAt: Date
    /// Which version of the prompt wrote `action`.
    ///
    /// A cache keyed only by message id would serve a line generated by a
    /// prompt that has since been rewritten — and the prompts here do get
    /// rewritten, because the model gets things wrong in ways only visible
    /// once they're on screen (see the grounding check in
    /// `MailSummaryGenerator`). Bumping `MailSummaryGenerator.promptVersion`
    /// retires every line written by the old one.
    var generatorVersion: Int

    var hasAction: Bool {
        !action.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    var hasGist: Bool {
        !gist.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    init(
        messageID: String,
        action: String,
        gist: String = "",
        dueDate: Date?,
        needsReply: Bool,
        savedAt: Date,
        generatorVersion: Int
    ) {
        self.messageID = messageID
        self.action = action
        self.gist = gist
        self.dueDate = dueDate
        self.needsReply = needsReply
        self.savedAt = savedAt
        self.generatorVersion = generatorVersion
    }

    /// Hand-written so a file from a build before this field existed still
    /// loads, on the same terms as `WorkdaySpan` — a summary with no version
    /// recorded is version zero, which no current prompt matches, so it is
    /// regenerated rather than discarded silently.
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        messageID = try container.decode(String.self, forKey: .messageID)
        action = try container.decodeIfPresent(String.self, forKey: .action) ?? ""
        gist = try container.decodeIfPresent(String.self, forKey: .gist) ?? ""
        dueDate = try container.decodeIfPresent(Date.self, forKey: .dueDate)
        needsReply = try container.decodeIfPresent(Bool.self, forKey: .needsReply) ?? false
        savedAt = try container.decodeIfPresent(Date.self, forKey: .savedAt) ?? Date()
        generatorVersion = try container.decodeIfPresent(Int.self, forKey: .generatorVersion) ?? 0
    }
}

/// Persists `MailSummary` under Application Support, mirroring
/// `DailyIntentionStore`, and prunes on the same 30-day rule as
/// `LiveEventStore` — a summary of a message that left the inbox weeks ago
/// is describing something nobody can act on.
final class MailSummaryStore {
    private let fileURL: URL

    private static let retentionDays: Double = 30

    init() {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        let dir = appSupport.appendingPathComponent("WorkActivityTracker", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        fileURL = dir.appendingPathComponent("mail-summaries.json")
    }

    func load() -> [String: MailSummary] {
        guard let data = try? Data(contentsOf: fileURL) else { return [:] }
        guard let decoded = try? JSONDecoder().decode([String: MailSummary].self, from: data) else {
            return [:]
        }
        return decoded
    }

    func save(_ summaries: [String: MailSummary]) {
        let cutoff = Date().addingTimeInterval(-Self.retentionDays * 86_400)
        let kept = summaries.filter { $0.value.savedAt > cutoff }
        guard let data = try? JSONEncoder().encode(kept) else { return }
        try? data.write(to: fileURL, options: .atomic)
    }

    @discardableResult
    func upsert(_ summary: MailSummary) -> [String: MailSummary] {
        var all = load()
        all[summary.messageID] = summary
        save(all)
        return all
    }
}
